# Generated by Django 6.0 on 2025-12-30 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rafeeq", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rafeeq.habit"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rafeeq.habit"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "habit")},
        ),
    ]
