import logging
from rafeeq import users
from rafeeq.habits.salah.scheduler import SalahHabit
from messaging import whatsapp

logger = logging.getLogger(__name__)

# Registry of available habits
# In V1, we only have Salah.
HABIT_REGISTRY = {
    "salah": SalahHabit()
}

def handle_incoming_message(from_number: str, message_body: str):
    """
    Main entry point for incoming WhatsApp messages.
    Routes the message to relevant habits based on user context.
    """
    logger.info(f"Dispatcher received message from {from_number}: {message_body}")
    
    # 1. Identify User
    user = users.get_user_by_phone(from_number)
    if not user:
        logger.warning(f"Message from unknown user: {from_number}")
        # V1: Ignore unknown users to prevent spam or unauthorized usage
        return

    # 2. Determine Context & Route
    # In V1, we don't have complex NLP or context tracking.
    # We will simply broadcast the message to all active habits for this user.
    # The habit is responsible for deciding if the message is relevant (e.g., "prayed", "missed").
    
    # For V1, strictly Salah.
    # Check if user is subscribed (conceptually, though table schema enforces it)
    # We could query db for subscriptions, but for V1 strictness let's assume if they exist 
    # and are interacting, it's about Salah.
    
    habit = HABIT_REGISTRY["salah"]
    
    # Delegate logic to the habit
    response_text = habit.handle_response(user, message_body)
    
    # 3. Send Response (if any)
    if response_text:
        whatsapp.send_message(from_number, response_text)
        logger.info(f"Sent response to {from_number}: {response_text}")
    else:
        logger.info("No response generated by habit.")

def handle_outbound_reminders():
    """
    Triggered by a cron/scheduler to check for due reminders.
    """
    # This might belong in a separate 'runner' module, but putting here for routing context.
    pass
